version: '3'

services:

  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  container_name: "spacead-db"

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    container_name: "spacead-app"
